[package]
name = "worktrace"
version = "0.4.0"
description = "A minimal desktop app that makes time and work tracking with issue tracking tools, like JIRA, easy."
authors = ["Sebastian Kasanzew"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "worktrace_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
base64 = "0.22.1"
gouqi = "0.20"
keyring = { version = "3.6.3", features = ["apple-native", "windows-native"] }
log = "0.4.28"
reqwest = { version = "0.12.14", features = ["blocking", "json"] }
rust-i18n = "3.1.5"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
specta = "2.0.0-rc.22"
specta-typescript = "0.0.9"
sys-locale = "0.3.2"
tauri = { version = "2.9.2", features = [] }
tauri-plugin-dialog = "2.4.2"
tauri-plugin-fs = "2.4.4"
tauri-plugin-log = "2.7.1"
tauri-plugin-opener = "2.5.2"
tauri-plugin-process = "2.3.1"
tauri-plugin-store = "2.4.1"
tauri-plugin-updater = "2.9.0"
tauri-specta = { version = "2.0.0-rc.21", features = ["derive", "typescript"] }
time = { version = "0.3.41", features = ["parsing", "formatting"] }
url = "2.5.7"

