// Generated by ts-to-zod
import { z } from "zod"

export const worklogTypeSchema = z.object({
  name: z.string(),
  shortCode: z.string(),
})

export const jiraAssigneeSchema = z.object({
  displayName: z.string(),
  emailAddress: z.string(),
})

export const jiraConfigSchema = z.object({
  url: z.string().nullable(),
  username: z.string().nullable(),
  password: z.string().nullable(),
})

export const jiraStatusCategorySchema = z.object({
  key: z.string(),
  name: z.string(),
})

export const jiraStatusSchema = z.object({
  name: z.string(),
  statusCategory: jiraStatusCategorySchema.nullable(),
})

export const jiraUserSessionSchema = z.object({
  name: z.string(),
})

export const jiraWorklogAuthorSchema = z.object({
  displayName: z.string(),
  emailAddress: z.string().nullable(),
  avatarUrls: z.array(z.tuple([z.string(), z.string()])).nullable(),
})

export const jiraWorklogSchema = z.object({
  id: z.string(),
  author: jiraWorklogAuthorSchema.nullable(),
  updateAuthor: jiraWorklogAuthorSchema.nullable(),
  comment: z.string().nullable(),
  created: z.string(),
  updated: z.string(),
  started: z.string(),
  timeSpent: z.string(),
  timeSpentSeconds: z.number(),
})

export const worklogPayloadSchema = z.object({
  timeSpentSeconds: z.number(),
  started: z.string(),
  comment: z.string(),
})

export const worklogResponseSchema = z.object({
  id: z.string(),
})

export const appSettingsSchema = z.object({
  jiraInstanceUrl: z.string(),
  jiraUsername: z.string(),
  jiraApiToken: z.string(),
  theme: z.string(),
  worklogTypes: z.array(worklogTypeSchema),
  defaultWorklogDescription: z.string(),
  enableAutomaticUpdates: z.boolean(),
  alwaysOnTop: z.boolean(),
})

export const jiraSubtaskFieldsSchema = z.object({
  summary: z.string(),
  status: jiraStatusSchema,
})

export const jiraWorklogListResponseSchema = z.object({
  worklogs: z.array(jiraWorklogSchema),
  total: z.number(),
  maxResults: z.number(),
  startAt: z.number(),
})

export const jiraSubtaskSchema = z.object({
  id: z.string(),
  key: z.string(),
  fields: jiraSubtaskFieldsSchema,
})

export const jiraFieldsSchema = z.object({
  summary: z.string(),
  status: jiraStatusSchema,
  assignee: jiraAssigneeSchema.nullable(),
  created: z.number(),
  updated: z.number(),
  subtasks: z.array(jiraSubtaskSchema),
})

export const jiraIssueSchema = z.object({
  id: z.string(),
  key: z.string(),
  fields: jiraFieldsSchema,
})

export const jiraSearchResponseSchema = z.object({
  issues: z.array(jiraIssueSchema),
  total: z.number(),
  isLast: z.boolean(),
})
