// Generated by ts-to-zod
import { z } from "zod";

export const jiraAssigneeSchema = z.object({
  displayName: z.string(),
  emailAddress: z.string(),
});

export const jiraConfigSchema = z.object({
  url: z.string().nullable(),
  username: z.string().nullable(),
  password: z.string().nullable(),
});

export const jiraStatusSchema = z.object({
  name: z.string(),
});

export const jiraFieldsSchema = z.object({
  summary: z.string(),
  status: jiraStatusSchema,
  assignee: jiraAssigneeSchema.nullable(),
  created: z.number(),
  updated: z.number(),
});

export const jiraIssueSchema = z.object({
  id: z.string(),
  key: z.string(),
  fields: jiraFieldsSchema,
});

export const jiraUserSessionSchema = z.object({
  name: z.string(),
});

export const jiraSearchResponseSchema = z.object({
  issues: z.array(jiraIssueSchema),
  total: z.number(),
  isLast: z.boolean(),
});
