// @ts-nocheck
// biome-ignore-all lint/suspicious/noExplicitAny: auto-generated code from tauri-specta
// biome-ignore-all lint/correctness/noUnusedImports: auto-generated code from tauri-specta
// This file is auto-generated by tauri-specta. Do not edit manually.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async jiraApiRequest(
    url: string,
    username: string,
    password: string,
    jql: string,
    apiVersion: string | null,
    authType: string | null
  ): Promise<Result<JiraSearchResponse, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("jira_api_request", {
          url,
          username,
          password,
          jql,
          apiVersion,
          authType,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async jiraGetCurrentUser(
    url: string,
    username: string,
    password: string
  ): Promise<Result<JiraUserSession, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("jira_get_current_user", { url, username, password }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async jiraAddWorklog(
    url: string,
    username: string,
    password: string,
    issueKey: string,
    payload: WorklogPayload,
    apiVersion: string | null,
    authType: string | null
  ): Promise<Result<WorklogResponse, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("jira_add_worklog", {
          url,
          username,
          password,
          issueKey,
          payload,
          apiVersion,
          authType,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async jiraUpdateWorklog(
    url: string,
    username: string,
    password: string,
    issueKey: string,
    worklogId: string,
    payload: WorklogPayload,
    apiVersion: string | null,
    authType: string | null
  ): Promise<Result<WorklogResponse, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("jira_update_worklog", {
          url,
          username,
          password,
          issueKey,
          worklogId,
          payload,
          apiVersion,
          authType,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async jiraDeleteWorklog(
    url: string,
    username: string,
    password: string,
    issueKey: string,
    worklogId: string,
    apiVersion: string | null,
    authType: string | null
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("jira_delete_worklog", {
          url,
          username,
          password,
          issueKey,
          worklogId,
          apiVersion,
          authType,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async jiraGetWorklogs(
    url: string,
    username: string,
    password: string,
    issueKey: string,
    apiVersion: string | null,
    authType: string | null
  ): Promise<Result<JiraWorklogListResponse, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("jira_get_worklogs", {
          url,
          username,
          password,
          issueKey,
          apiVersion,
          authType,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async saveJiraConfig(settings: JiraSettings): Promise<Result<null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("save_jira_config", { settings }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async getJiraConfig(): Promise<Result<JiraSettings | null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_jira_config") }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async clearJiraConfig(): Promise<Result<null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("clear_jira_config") }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async getAppSettings(): Promise<Result<AppSettings, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_app_settings") }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async saveAppSettings(settings: AppSettings): Promise<Result<null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("save_app_settings", { settings }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async setMiniMode(enable: boolean): Promise<Result<null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("set_mini_mode", { enable }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
}

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

/**
 * Application settings
 */
export type AppSettings = { general: GeneralSettings; jira: JiraSettings | null }
/**
 * General application settings
 */
export type GeneralSettings = {
  theme: string
  worklogTypes: WorklogType[]
  defaultWorklogDescription: string
  enableAutomaticUpdates: boolean
  alwaysOnTop: boolean
  customIssueKeys: string[]
}
/**
 * JIRA issue assignee
 */
export type JiraAssignee = { displayName: string; emailAddress: string }
/**
 * JIRA issue fields
 */
export type JiraFields = {
  summary: string
  status: JiraStatus
  assignee: JiraAssignee | null
  /**
   * Unix timestamp in milliseconds (for JavaScript Date compatibility)
   */
  created: number
  /**
   * Unix timestamp in milliseconds (for JavaScript Date compatibility)
   */
  updated: number
  subtasks: JiraSubtask[]
}
/**
 * JIRA issue
 */
export type JiraIssue = { id: string; key: string; fields: JiraFields }
/**
 * JIRA search API response
 */
export type JiraSearchResponse = { issues: JiraIssue[]; total: number; isLast: boolean }
/**
 * JIRA configuration stored in app settings
 */
export type JiraSettings = {
  instanceUrl: string
  username: string
  apiToken: string
  apiVersion?: string
  authType?: string
}
/**
 * JIRA issue status
 */
export type JiraStatus = { name: string; statusCategory: JiraStatusCategory | null }
/**
 * JIRA status category
 */
export type JiraStatusCategory = { key: string; name: string }
/**
 * JIRA subtask
 */
export type JiraSubtask = { id: string; key: string; fields: JiraSubtaskFields }
/**
 * JIRA subtask fields
 */
export type JiraSubtaskFields = { summary: string; status: JiraStatus }
/**
 * JIRA current user session info
 */
export type JiraUserSession = { name: string; apiVersion: string; authType: string }
/**
 * JIRA worklog
 */
export type JiraWorklog = {
  id: string
  author: JiraWorklogAuthor | null
  updateAuthor: JiraWorklogAuthor | null
  comment: string | null
  created: string
  updated: string
  started: string
  timeSpent: string
  timeSpentSeconds: number
}
/**
 * JIRA worklog author
 */
export type JiraWorklogAuthor = {
  displayName: string
  emailAddress: string | null
  avatarUrls: [string, string][] | null
}
/**
 * JIRA worklog list response
 */
export type JiraWorklogListResponse = {
  worklogs: JiraWorklog[]
  total: number
  maxResults: number
  startAt: number
}
/**
 * Worklog payload for creating a worklog in JIRA
 */
export type WorklogPayload = { timeSpentSeconds: number; started: string; comment: string }
/**
 * Minimal worklog response
 */
export type WorklogResponse = { id: string }
/**
 * Worklog type configuration
 */
export type WorklogType = { name: string; shortCode: string }

/** tauri-specta globals **/

import { Channel as TAURI_CHANNEL, invoke as TAURI_INVOKE } from "@tauri-apps/api/core"
import * as TAURI_API_EVENT from "@tauri-apps/api/event"
import type { WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow"

type __EventObj__<T> = {
  listen: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.listen<T>>
  once: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.once<T>>
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>
}

export type Result<T, E> = { status: "ok"; data: T } | { status: "error"; error: E }

function __makeEvents__<T extends Record<string, any>>(mappings: Record<keyof T, string>) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & ((handle: __WebviewWindow__) => __EventObj__<T[K]>)
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T]

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case "listen":
                return (arg: any) => TAURI_API_EVENT.listen(name, arg)
              case "once":
                return (arg: any) => TAURI_API_EVENT.once(name, arg)
              case "emit":
                return (arg: any) => TAURI_API_EVENT.emit(name, arg)
            }
          },
        })
      },
    }
  )
}
