#[cfg(debug_assertions)]
pub fn export_bindings() {
    use specta_typescript::Typescript;
    use tauri_specta::{Builder, collect_commands};

    let builder = Builder::<tauri::Wry>::new().commands(collect_commands![
        crate::jira::issues::jira_api_request,
        crate::jira::auth::jira_get_current_user,
        crate::jira::worklogs::jira_add_worklog,
        crate::jira::worklogs::jira_update_worklog,
        crate::jira::worklogs::jira_delete_worklog,
        crate::jira::worklogs::jira_get_worklogs,
        crate::jira::worklogs::jira_get_user_worklogs_by_date_range,
        crate::jira::config::save_jira_config,
        crate::jira::config::get_jira_config,
        crate::jira::config::clear_jira_config,
        crate::jira::config::get_app_settings,
        crate::jira::config::save_app_settings,
        crate::set_mini_mode,
    ]);

    builder
        .export(
            Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header(
                    "// @ts-nocheck\n// biome-ignore-all lint/suspicious/noExplicitAny: auto-generated code from tauri-specta\n// biome-ignore-all lint/correctness/noUnusedImports: auto-generated code from tauri-specta\n// This file is auto-generated by tauri-specta. Do not edit manually.\n",
                ),
            "../src/types/bindings.ts",
        )
        .expect("Failed to export typescript bindings");

    let pnpm_cmd = if cfg!(target_os = "windows") {
        "pnpm.cmd"
    } else {
        "pnpm"
    };

    // Auto-fix the generated file with biome (format + fixable lints)
    let status = std::process::Command::new(pnpm_cmd)
        .args(["biome", "check", "--write", "src/types/bindings.ts"])
        .current_dir("..")
        .status();

    if let Err(e) = status {
        log::warn!("Failed to run biome on generated bindings: {}", e);
    }

    // Generate Zod schemas from the freshly formatted bindings
    match std::process::Command::new(pnpm_cmd)
        .args(["run", "gen:zod:bindings"])
        .current_dir("..")
        .status()
    {
        Ok(exit) if exit.success() => {}
        Ok(exit) => {
            log::warn!("ts-to-zod generation exited with non-zero status: {}", exit);
        }
        Err(e) => {
            log::warn!("Failed to run ts-to-zod for bindings: {}", e);
        }
    }
}
